name: server
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.0

dependencies:
  shelf: ^1.4.2
  shelf_router: ^1.1.2
  mongo_dart: ^0.10.3
  dart_jsonwebtoken: ^2.14.0
  bcrypt: ^1.1.3
  dotenv: ^4.2.0
  shelf_cors_headers: ^0.1.5

dev_dependencies:
  http: ^1.2.2
  lints: ^6.0.0
  test: ^1.25.6
